spring:
  application:
      name: apiClient
  kafka:
    bootstrap-servers: localhost:9092
    topic: sendEmail
    consumer:
      auto-offset-reset: earliest
    properties:
      security.protocol: PLAINTEXT
      enable.idempotence: true
      request.timeout.ms: 60000
      max.in.flight.requests.per.connection: 5
    admin:
      properties:
        request.timeout.ms: 30000


