// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sys_ticket;

#nullable disable

namespace sys_ticket.Migrations
{
    [DbContext(typeof(Context_ticket))]
    partial class Context_ticketModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SysAdmin.Models.TicketData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("aliases")
                        .HasColumnType("longtext");

                    b.Property<decimal>("amountTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("bag_back")
                        .HasColumnType("int");

                    b.Property<int>("bag_go")
                        .HasColumnType("int");

                    b.Property<string>("birthOfDay")
                        .HasColumnType("longtext");

                    b.Property<string>("customType")
                        .HasColumnType("longtext");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("fullName")
                        .HasColumnType("longtext");

                    b.Property<string>("orderNo")
                        .HasColumnType("longtext");

                    b.Property<string>("orderNoCustomer")
                        .HasColumnType("longtext");

                    b.Property<string>("phone")
                        .HasColumnType("longtext");

                    b.Property<string>("seats_back")
                        .HasColumnType("longtext");

                    b.Property<string>("seats_back_child")
                        .HasColumnType("longtext");

                    b.Property<string>("seats_go")
                        .HasColumnType("longtext");

                    b.Property<string>("seats_go_child")
                        .HasColumnType("longtext");

                    b.Property<string>("ticketType")
                        .HasColumnType("longtext");

                    b.Property<string>("ticketTypeBack")
                        .HasColumnType("longtext");

                    b.Property<string>("ticketTypeGo")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("ticket_data");
                });
#pragma warning restore 612, 618
        }
    }
}
