spring:
  application:
    name: ticket

  datasource:
    url: jdbc:mysql://localhost:3300/db_sys_book_flightg

    username: root
    password: Vu123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
      show_sql: true
server:
  port: 1002
appConfig:
  default-page-size: 10
  default-page-number: 0
  jmx:
    enabled: false


