spring:
  application:
    name: login

  datasource:
    url: jdbc:mysql://localhost:3300/projectK4
    username: root
    password: Vu123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8081/realms/projectK4
#        opaquetoken:
#          client-id: projectK4
#          client-secret: ba7t3nsIG8ZdghdvFyBT4aclkALQxa8i
jwt:
  auth:
    converter:
      resource-id: projectK4
      principle-attribute: preferred_username
token :
  enpont: http://localhost:8081/realms/projectK4/protocol/openid-connect/token

application:
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000
        refresh-token:
          expiration: 604800000

server:
  port: 1001


