

spring :
  application:
      name: Vnpay
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order_group
      auto-offset-reset: earliest
      properties:
        security.protocol: PLAINTEXT
        enable.idempotence: true
        request.timeout.ms: 60000
        max.in.flight.requests.per.connection: 5
    admin:
      properties:
        request.timeout.ms: 30000
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenkhacvu1997@gmail.com
    password: wfad udob rtad etme
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
server:
  port: 1003